name: Setup DEP package manager
description: Installs the DEP package manager into the runner

runs:
  using: "composite"
  steps:
    - run: cp dist/dep /usr/local/bin/dep
      shell: bash
    - run: chmod +x /usr/local/bin/dep
      shell: bash
