name: Setup DEP package manager
description: Installs the DEP package manager into the runner

runs:
  using: "composite"
  steps:
    - run: curl --location https://raw.githubusercontent.com/finwo/dep/master/dist/dep --output /usr/local/bin/dep
    - run: chmod +x /usr/local/bin/dep
