name: Setup DEP package manager
description: Installs the DEP package manager into the runner

runs:
  using: "composite"
  steps:

    - shell: bash
      run: |
        echo "${GITHUB_ACTION_PATH}/dist" >> $GITHUB_PATH
        dep repository add finwo 'https://github.com/finwo/dep-repository/archive/refs/heads/main.tar.gz'
        dep repository update
