name: Setup DEP package manager
description: Installs the DEP package manager into the runner

runs:
  using: "composite"
  steps:

    - if: runner.os == 'Linux'
      shell: bash
      run: |
        echo "dist" >> $GITHUB_PATH

    - if: runner.os == 'Windows'
      shell: pwsh
      run: |
        echo "dist" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - if: runner.os == 'Linux'
      run: env

    - if: runner.os == 'Windows'
      run: set
