#!/usr/bin/env bash

# Useful function
# See http://wiki.bash-hackers.org/howto/conffile
clean_conf () {
  # check if the file contains something we don't want
  if egrep -q -v '^#|^[^ ]*=[^;]*' "$1"; then
    echo "Config file ($1) is unclean, cleaning it..." >&2
    # filter the original to a new file
    mv $1 $1.bak
    egrep '^#|^[^ ]*=[^;&]*'  "$1.bak" > "$1"
  fi
}

# Make sure the required stuff exists
[ -d ~/.cdeps ] || mkdir -p ~/.cdeps
[ -f ~/.cdeps/config ] || touch ~/.cdeps/config
[ -f ~/.cdeps/repositories ] || touch ~/.cdeps/repositories

# Load the user's configuration
clean_conf ~/.cdeps/config
source ~/.cdeps/config

case "$1" in
  init)
    
    ;;
  add)
    ;;
  install)
    ;;
  help)
    cat <<EOF

LICENSE

The MIT License (MIT)

Copyright (c) 2017 Robin Bron

Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the "Software"), to deal in
the Software without restriction, including without limitation the rights to
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
the Software, and to permit persons to whom the Software is furnished to do so,
subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

EOF
    ;;
  *)
    # Check for user-defined
    if command -v $0-$1 &>/dev/null; then
      $0-$1 "${@:2}"
    else
      echo "Usage: $0 (repo|init|add|install|help)"
      exit 1
    fi
    ;;
esac
