#!/usr/bin/env bash

# Useful function
# See http://wiki.bash-hackers.org/howto/conffile
clean_conf () {
  # check if the file contains something we don't want
  if egrep -q -v '^#|^[^ ]*=[^;]*' "$1"; then
    echo "Config file ($1) is unclean, cleaning it..." >&2
    # filter the original to a new file
    mv $1 $1.bak
    egrep '^#|^[^ ]*=[^;&]*'  "$1.bak" > "$1"
  fi
}

# Load the user's configuration
[ -f ~/.cdeps/config ] && {
  clean_conf ~/.cdeps/config
  source ~/.cdeps/config
}

case "$1" in
  init)
    [ -d ~/.cdeps ] || mkdir -p ~/.cdeps
    
    ;;
  add)
    ;;
  install)
    ;;
  *)
    # Check for user-defined
    if command -v $0-$1 &>/dev/null; then
      $0-$1 "${@:2}"
    else
      echo "Usage: $0 (repo|init|add|install)"
      exit 1
    fi
    ;;
esac
