#!/usr/bin/env bash

# Make sure the required stuff exists
[ -d ~/.dep ] || mkdir -p ~/.dep
[ -f ~/.dep/repositories ] || {
  echo "https://github.com/cdeps/dep-repository/archive/master.tar.gz" > ~/.dep/repositories
}

# Regex for validating URLs
# https://stackoverflow.com/a/3184819
urlcheck='^(https?|ftp|file)://[-A-Za-z0-9\+&@#/%?=~_|!:,.;]*[-A-Za-z0-9\+&@#/%=~_|]$'

case "$1" in
  help)
    echo "Usage: $0 command"
    echo ""
    echo "Commands:"
    echo "  help          Show this help info"
    echo "  list          List all repositories in use"
    echo "  add   <url>   Add a repository"
    echo "  clean         Remove dependency cache"
    echo "  update        Update dependency cache"
    echo ""
    ;;

  list)
    cat ~/.dep/repositories
    ;;

  add)

    # The user must give a url we're using
    if [[ -z "$2" ]]; then
      echo "No repository url given" >&2
      exit 1
    fi

    # The url must be valid
    [[ "$2" =~ $urlcheck ]] || {
      echo "Given url is not valid" >&2
      exit 1
    }

    # Save, further checks haven't been written
    echo "$2" >> ~/.dep/repositories
    echo "The following URL was added: $2"
    ;;

  clean)

    # Remove all packages
    rm -rf ~/.dep/packages && {
      echo "All packages have been removed"
      echo "Please run '$0 update' to fetch up-to-date versions"
    } || {
      echo "Unable to remove all packages" >&2
      echo "Please check the permissions for ~/.dep/packages" >&2
      exit 1
    }

    ;;

  update)

    # Make sure the extraction folder exists
    [ -d ~/.dep/packages ] || {
      mkdir -p ~/.dep/packages
    }

    # Simply download all package references
    cd ~/.dep/packages
    for i in $(cat ~/.dep/repositories); do
      curl -fL# "$i" | tar --strip-components=1 -xzf -
    done

    ;;
  remove)

    # Notify this is a todo
    echo "This call is not implemented yet" >&2
    echo "To remove a repository, please manually edit the following file:" >&2
    echo "  ~/.dep/repositories" >&2
    exit 1

    ;;
  *)
    echo "Usage: $0 (list|add|clean|update|remove)"
    exit 1
    ;;
esac
